# Темы: https://github.com/alacritty/alacritty-theme
import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"
opacity = 1.00
blur = false

[font]
normal.family = "JetBrains Mono"
size = 13.0
